import type { ResourceDef } from './resource-types';

export const projectDef: ResourceDef = {
  key: 'projects',
  basePath: '/projects',
  title: 'Projects',
  singular: 'Project',
  endpoint: '/projects',
  perm: 'construction.project',
  searchable: true,
  editable: true,
  columns: [
    { key: 'code', label: 'Code' },
    { key: 'name', label: 'Project' },
    { key: 'clientName', label: 'Client' },
    { key: 'location', label: 'Location' },
    { key: 'contractValue', label: 'Contract value', format: 'money' },
    { key: 'billed', label: 'Billed', format: 'money' },
    { key: 'cost', label: 'Cost to date', format: 'money' },
    { key: 'endDate', label: 'Due', format: 'date' },
    { key: 'status', label: 'Status', format: 'status' },
  ],
  filters: [{ name: 'status', label: 'Status', type: 'select', options: ['planning', 'active', 'on_hold', 'completed', 'cancelled'] }],
  form: {
    fields: [
      { name: 'code', label: 'Project code', required: true },
      { name: 'name', label: 'Project name', required: true, span: 3 },
      { name: 'clientId', label: 'Client', type: 'select', source: { endpoint: '/parties?type=customer&pageSize=200', label: (r) => r.name }, span: 2 },
      { name: 'contractNo', label: 'Contract / work order no.' },
      { name: 'contractValue', label: 'Contract value (BDT)', type: 'decimal', default: '0' },
      { name: 'location', label: 'Site location', span: 2 },
      { name: 'startDate', label: 'Start date', type: 'date' },
      { name: 'endDate', label: 'Completion date', type: 'date' },
      { name: 'projectManagerId', label: 'Project manager', type: 'select', source: { endpoint: '/employees/pick', label: (r) => `${r.code} — ${r.name}` } },
      { name: 'status', label: 'Status', type: 'select', options: ['planning', 'active', 'on_hold', 'completed', 'cancelled'], default: 'planning' },
      { name: 'retentionPercent', label: 'Retention % (client)', type: 'decimal', default: '10' },
      { name: 'vatPercent', label: 'VAT % on bills', type: 'decimal', default: '7.5', hint: 'Needs a matching VAT code' },
      { name: 'mobilizationAdvance', label: 'Mobilization advance', type: 'decimal', default: '0' },
      { name: 'advanceRecoveryPercent', label: 'Advance recovery % per bill', type: 'decimal', default: '10' },
      { name: 'createSiteStore', label: 'Create site store', type: 'checkbox', default: true, createOnly: true },
      { name: 'description', label: 'Description', type: 'textarea', span: 4 },
    ],
  },
};
