import Link from 'next/link';
import type { ColumnDef, FieldDef, LinesDef, ResourceDef, Row } from './resource-types';
import { today } from './format';
import { GoodsReceiptPanel, IssueFromRequisitionPanel, SubcontractBillPanel } from '@/components/doc-extras';

const statusCol = (key = 'status'): ColumnDef => ({ key, label: 'Status', format: 'status' });
const statusFilter = (options: string[]): FieldDef => ({ name: 'status', label: 'Status', type: 'select', options });
const projectField: FieldDef = { name: 'projectId', label: 'Project', type: 'select', source: { lookup: 'projects', label: (r) => `${r.code} — ${r.name}` } };
const projectFilter: FieldDef = { ...projectField };
const itemSource = { endpoint: '/items/pick', label: (r: Row) => `${r.code} — ${r.name} (${r.uom})` };
const partySource = (type?: string) => ({ endpoint: `/parties?pageSize=200${type ? `&type=${type}` : ''}`, label: (r: Row) => r.name });
const employeeSource = { endpoint: '/employees/pick', label: (r: Row) => `${r.code} — ${r.name}` };
const vatSource = { lookup: 'taxCodes', filter: (r: Row) => r.kind === 'vat', label: (r: Row) => r.name };
const warehouseSource = { lookup: 'warehouses', label: (r: Row) => `${r.code} — ${r.name}` };
const accountSource = (filter?: (r: Row) => boolean) => ({
  lookup: 'accounts',
  filter: (r: Row) => !r.isGroup && (!filter || filter(r)),
  label: (r: Row) => `${r.code} — ${r.name}`,
});
const docLink = (base: string, idKey: string, title: string): ColumnDef => ({
  key: idKey,
  label: title,
  render: (r) => (r[idKey] ? <Link className="text-brand-600 hover:underline" href={`${base}/${r[idKey]}`}>View →</Link> : '—'),
});

const priceLines = (withVat = true, withAccount?: 'income' | 'expense'): LinesDef => ({
  columns: [
    { name: 'itemId', label: 'Item', type: 'select', source: itemSource, width: '22%', onPick: (it, l) => ({ ...l, description: l.description || it.name, unitPrice: l.unitPrice || it.standardCost || '', vatCodeId: l.vatCodeId || it.defaultVatCodeId || '' }) },
    { name: 'description', label: 'Description', width: '26%' },
    { name: 'quantity', label: 'Qty', type: 'decimal', width: '9%' },
    { name: 'unitPrice', label: 'Rate', type: 'decimal', width: '11%' },
    ...(withVat ? [{ name: 'vatCodeId', label: 'VAT', type: 'select' as const, source: vatSource, width: '13%' }] : []),
    ...(withAccount
      ? [{ name: 'accountId', label: withAccount === 'income' ? 'Income a/c' : 'Expense a/c', type: 'select' as const, source: accountSource((r) => r.type === withAccount), width: '15%' }]
      : []),
  ],
  newLine: () => ({ itemId: '', description: '', quantity: '1', unitPrice: '', vatCodeId: '', accountId: '' }),
  amount: (l) => Number(l.quantity || 0) * Number(l.unitPrice || 0),
});

const qtyLines = (extra: LinesDef['columns'] = []): LinesDef => ({
  columns: [{ name: 'itemId', label: 'Item', type: 'select', source: itemSource, width: '40%' }, { name: 'quantity', label: 'Quantity', type: 'decimal', width: '15%' }, ...extra],
  newLine: () => ({ itemId: '', quantity: '' }),
});

export const RESOURCES: Record<string, ResourceDef> = {
  // ---------------- HR ----------------
  employees: {
    key: 'employees',
    title: 'Employees',
    singular: 'Employee',
    endpoint: '/employees',
    perm: 'hr.employee',
    importResource: 'employees',
    searchable: true,
    editable: true,
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name', label: 'Name', render: (r) => `${r.firstName} ${r.lastName ?? ''}` },
      { key: 'designationName', label: 'Designation' },
      { key: 'departmentName', label: 'Department' },
      { key: 'projectName', label: 'Current Project' },
      { key: 'employmentType', label: 'Type', format: 'status' },
      { key: 'phone', label: 'Phone' },
      statusCol(),
    ],
    filters: [
      statusFilter(['active', 'resigned', 'terminated']),
      { name: 'employmentType', label: 'Type', type: 'select', options: ['permanent', 'contract', 'probation', 'daily_wage'] },
      { name: 'departmentId', label: 'Department', type: 'select', source: { lookup: 'departments' } },
      projectFilter,
    ],
    form: {
      fields: [
        { name: 'code', label: 'Employee code', hint: 'Leave blank to auto-generate', createOnly: true },
        { name: 'firstName', label: 'First name', required: true },
        { name: 'lastName', label: 'Last name' },
        { name: 'gender', label: 'Gender', type: 'select', options: ['male', 'female', 'other'] },
        { name: 'fatherName', label: "Father's name" },
        { name: 'motherName', label: "Mother's name" },
        { name: 'dateOfBirth', label: 'Date of birth', type: 'date' },
        { name: 'bloodGroup', label: 'Blood group', type: 'select', options: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'] },
        { name: 'nid', label: 'NID' },
        { name: 'tin', label: 'TIN' },
        { name: 'phone', label: 'Phone' },
        { name: 'email', label: 'Email', type: 'email' },
        { name: 'presentAddress', label: 'Present address', type: 'textarea', span: 2 },
        { name: 'permanentAddress', label: 'Permanent address', type: 'textarea', span: 2 },
        { name: 'departmentId', label: 'Department', type: 'select', source: { lookup: 'departments' } },
        { name: 'designationId', label: 'Designation', type: 'select', source: { lookup: 'designations' } },
        { name: 'branchId', label: 'Branch', type: 'select', source: { lookup: 'branches' } },
        { name: 'managerId', label: 'Reports to', type: 'select', source: employeeSource },
        { name: 'employmentType', label: 'Employment type', type: 'select', options: ['permanent', 'contract', 'probation', 'daily_wage'], default: 'permanent', required: true },
        { name: 'dailyWage', label: 'Daily wage (BDT)', type: 'decimal', showIf: (v) => v.employmentType === 'daily_wage' },
        { name: 'joiningDate', label: 'Joining date', type: 'date', required: true, default: today() },
        { name: 'confirmationDate', label: 'Confirmation date', type: 'date' },
        { name: 'currentProjectId', label: 'Assigned project', type: 'select', source: { lookup: 'projects', label: (r) => `${r.code} — ${r.name}` } },
        { name: 'status', label: 'Status', type: 'select', options: ['active', 'resigned', 'terminated'], default: 'active' },
        { name: 'exitDate', label: 'Exit date', type: 'date', showIf: (v) => v.status && v.status !== 'active' },
        { name: 'bankName', label: 'Bank' },
        { name: 'bankAccountNo', label: 'Bank account no.' },
        { name: 'mobileBankingNo', label: 'bKash / Nagad no.' },
        { name: 'emergencyContactName', label: 'Emergency contact' },
        { name: 'emergencyContactPhone', label: 'Emergency phone' },
      ],
    },
  },
  departments: {
    key: 'departments',
    title: 'Departments',
    singular: 'Department',
    endpoint: '/departments',
    perm: 'hr.department',
    importResource: 'departments',
    searchable: true,
    editable: true,
    columns: [{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'isActive', label: 'Active', format: 'bool' }],
    form: {
      fields: [
        { name: 'code', label: 'Code', required: true },
        { name: 'name', label: 'Name', required: true },
        { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      ],
    },
  },
  designations: {
    key: 'designations',
    title: 'Designations',
    singular: 'Designation',
    endpoint: '/designations',
    perm: 'hr.designation',
    importResource: 'designations',
    searchable: true,
    editable: true,
    columns: [{ key: 'name', label: 'Name' }, { key: 'grade', label: 'Grade' }],
    form: { fields: [{ name: 'name', label: 'Name', required: true }, { name: 'grade', label: 'Grade' }] },
  },
  holidays: {
    key: 'holidays',
    title: 'Public Holidays',
    singular: 'Holiday',
    endpoint: '/holidays',
    perm: 'hr.attendance',
    editable: true,
    columns: [{ key: 'date', label: 'Date', format: 'date' }, { key: 'name', label: 'Holiday' }],
    form: { fields: [{ name: 'date', label: 'Date', type: 'date', required: true }, { name: 'name', label: 'Name', required: true }] },
  },
  'leave-types': {
    key: 'leave-types',
    title: 'Leave Types',
    singular: 'Leave Type',
    endpoint: '/leave-types',
    perm: 'hr.leave',
    editable: true,
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name', label: 'Name' },
      { key: 'daysPerYear', label: 'Days / year' },
      { key: 'isPaid', label: 'Paid', format: 'bool' },
      { key: 'carryForward', label: 'Carry forward', format: 'bool' },
    ],
    form: {
      fields: [
        { name: 'code', label: 'Code', required: true },
        { name: 'name', label: 'Name', required: true },
        { name: 'daysPerYear', label: 'Days per year', type: 'number', required: true },
        { name: 'isPaid', label: 'Paid leave', type: 'checkbox', default: true },
        { name: 'carryForward', label: 'Carry forward', type: 'checkbox' },
      ],
    },
  },
  'leave-requests': {
    key: 'leave-requests',
    title: 'Leave Requests',
    singular: 'Leave Request',
    endpoint: '/leave/requests',
    perm: 'hr.leave',
    noLink: true,
    columns: [
      { key: 'employeeCode', label: 'Code' },
      { key: 'employeeName', label: 'Employee' },
      { key: 'leaveType', label: 'Type' },
      { key: 'fromDate', label: 'From', format: 'date' },
      { key: 'toDate', label: 'To', format: 'date' },
      { key: 'days', label: 'Days', format: 'qty' },
      { key: 'reason', label: 'Reason' },
      statusCol(),
    ],
    filters: [statusFilter(['pending', 'approved', 'rejected'])],
    form: {
      fields: [
        { name: 'employeeId', label: 'Employee', type: 'select', source: employeeSource, required: true, span: 2 },
        { name: 'leaveTypeId', label: 'Leave type', type: 'select', source: { lookup: 'leaveTypes' }, required: true },
        { name: 'fromDate', label: 'From', type: 'date', required: true, default: today() },
        { name: 'toDate', label: 'To', type: 'date', required: true, default: today() },
        { name: 'reason', label: 'Reason', type: 'textarea', span: 2 },
      ],
    },
    rowActions: [
      { label: 'Approve', path: (r) => `/leave/requests/${r.id}/decision`, body: () => ({ status: 'approved' }), when: (r) => r.status === 'pending', perm: 'hr.leave.approve' },
      { label: 'Reject', path: (r) => `/leave/requests/${r.id}/decision`, body: () => ({ status: 'rejected' }), when: (r) => r.status === 'pending', perm: 'hr.leave.approve', variant: 'danger' },
    ],
  },

  // ---------------- Construction ----------------
  'site-requisitions': {
    key: 'site-requisitions',
    title: 'Site Requisitions',
    singular: 'Site Requisition',
    endpoint: '/site-requisitions',
    perm: 'construction.requisition',
    searchable: true,
    columns: [{ key: 'no', label: 'No.' }, { key: 'date', label: 'Date', format: 'date' }, { key: 'projectName', label: 'Project' }, { key: 'requiredBy', label: 'Required by', format: 'date' }, { key: 'remarks', label: 'Remarks' }, statusCol()],
    filters: [statusFilter(['draft', 'submitted', 'approved', 'partially_fulfilled', 'fulfilled', 'rejected']), projectFilter],
    form: {
      fields: [
        { ...projectField, required: true, name: 'projectId' },
        { name: 'date', label: 'Date', type: 'date', required: true, default: today() },
        { name: 'requiredBy', label: 'Required by', type: 'date' },
        { name: 'remarks', label: 'Remarks', type: 'textarea', span: 4 },
      ],
      lines: qtyLines([{ name: 'remarks', label: 'Remarks', width: '35%' }]),
    },
    detail: {
      fields: [{ key: 'no', label: 'No.' }, { key: 'projectName', label: 'Project' }, { key: 'date', label: 'Date', format: 'date' }, { key: 'requiredBy', label: 'Required by', format: 'date' }, statusCol(), { key: 'remarks', label: 'Remarks' }],
      lines: {
        key: 'lines',
        columns: [{ key: 'itemCode', label: 'Code' }, { key: 'itemName', label: 'Item' }, { key: 'uom', label: 'Unit' }, { key: 'quantity', label: 'Requested', format: 'qty' }, { key: 'issuedQty', label: 'Issued', format: 'qty' }, { key: 'pendingQty', label: 'Pending', format: 'qty' }],
      },
      actions: [
        { label: 'Submit', path: (r) => `/site-requisitions/${r.id}/submit`, when: (r) => r.status === 'draft' },
        { label: 'Approve', path: (r) => `/site-requisitions/${r.id}/approve`, when: (r) => ['draft', 'submitted'].includes(r.status), perm: 'construction.requisition.update' },
        { label: 'Reject', path: (r) => `/site-requisitions/${r.id}/reject`, when: (r) => ['draft', 'submitted'].includes(r.status), variant: 'danger' },
        {
          label: 'Raise purchase requisition',
          path: (r) => `/site-requisitions/${r.id}/purchase-requisition`,
          when: (r) => ['approved', 'partially_fulfilled'].includes(r.status),
          perm: 'procurement.requisition.create',
          variant: 'secondary',
          redirect: (res) => `/m/purchase-requisitions/${res.id}`,
        },
      ],
      extra: (r) => (['approved', 'partially_fulfilled'].includes(r.status) ? <IssueFromRequisitionPanel requisition={r} /> : null),
    },
  },
  'work-orders': {
    key: 'work-orders',
    title: 'Subcontract Work Orders',
    singular: 'Work Order',
    endpoint: '/work-orders',
    perm: 'construction.subcontract',
    searchable: true,
    columns: [{ key: 'no', label: 'No.' }, { key: 'date', label: 'Date', format: 'date' }, { key: 'partyName', label: 'Subcontractor' }, { key: 'projectName', label: 'Project' }, { key: 'value', label: 'Value', format: 'money' }, { key: 'billed', label: 'Billed', format: 'money' }, statusCol()],
    filters: [projectFilter],
    form: {
      fields: [
        { ...projectField, required: true },
        { name: 'partyId', label: 'Subcontractor', type: 'select', source: partySource('subcontractor'), required: true },
        { name: 'date', label: 'Date', type: 'date', required: true, default: today() },
        { name: 'retentionPercent', label: 'Retention %', type: 'decimal', default: '5' },
        { name: 'scope', label: 'Scope of work', type: 'textarea', span: 4 },
      ],
      lines: {
        columns: [
          { name: 'description', label: 'Description', width: '45%' },
          { name: 'uom', label: 'Unit', width: '10%' },
          { name: 'quantity', label: 'Qty', type: 'decimal', width: '15%' },
          { name: 'rate', label: 'Rate', type: 'decimal', width: '15%' },
        ],
        newLine: () => ({ description: '', uom: '', quantity: '', rate: '' }),
        amount: (l) => Number(l.quantity || 0) * Number(l.rate || 0),
      },
    },
    detail: {
      fields: [{ key: 'no', label: 'No.' }, { key: 'partyName', label: 'Subcontractor' }, { key: 'projectName', label: 'Project' }, { key: 'date', label: 'Date', format: 'date' }, { key: 'value', label: 'Value', format: 'money' }, { key: 'retentionPercent', label: 'Retention %', format: 'qty' }, statusCol(), { key: 'scope', label: 'Scope' }],
      lines: {
        key: 'lines',
        columns: [{ key: 'description', label: 'Description' }, { key: 'uom', label: 'Unit' }, { key: 'quantity', label: 'Qty', format: 'qty' }, { key: 'executedQty', label: 'Executed', format: 'qty' }, { key: 'rate', label: 'Rate', format: 'money' }, { key: 'amount', label: 'Amount', format: 'money' }],
      },
      extra: (r) => <SubcontractBillPanel workOrder={r} />,
    },
  },
  'ra-bills': {
    key: 'ra-bills',
    title: 'Running Account (RA) Bills',
    singular: 'RA Bill',
    endpoint: '/ra-bills',
    perm: 'construction.rabill',
    createHref: '/construction/ra-bills/new',
    columns: [
      { key: 'no', label: 'No.' },
      { key: 'date', label: 'Date', format: 'date' },
      { key: 'projectName', label: 'Project' },
      { key: 'grossAmount', label: 'Gross', format: 'money' },
      { key: 'retentionAmount', label: 'Retention', format: 'money' },
      { key: 'advanceRecovery', label: 'Adv. recovery', format: 'money' },
      { key: 'vatAmount', label: 'VAT', format: 'money' },
      { key: 'netAmount', label: 'Net receivable', format: 'money' },
      statusCol(),
    ],
    filters: [projectFilter, statusFilter(['draft', 'approved', 'cancelled'])],
    detail: {
      fields: [
        { key: 'no', label: 'No.' },
        { key: 'projectName', label: 'Project' },
        { key: 'clientName', label: 'Client' },
        { key: 'date', label: 'Date', format: 'date' },
        { key: 'periodTo', label: 'Period to', format: 'date' },
        statusCol(),
        { key: 'grossAmount', label: 'Gross value of work', format: 'money' },
        { key: 'retentionAmount', label: 'Less: retention', format: 'money' },
        { key: 'advanceRecovery', label: 'Less: advance recovery', format: 'money' },
        { key: 'vatAmount', label: 'Add: VAT', format: 'money' },
        { key: 'netAmount', label: 'Net receivable', format: 'money' },
        docLink('/m/invoices', 'invoiceId', 'Client invoice'),
      ],
      lines: {
        key: 'lines',
        columns: [
          { key: 'code', label: 'BOQ' },
          { key: 'description', label: 'Description' },
          { key: 'uom', label: 'Unit' },
          { key: 'boqQty', label: 'BOQ qty', format: 'qty' },
          { key: 'previousQty', label: 'Previous', format: 'qty' },
          { key: 'currentQty', label: 'This bill', format: 'qty' },
          { key: 'cumulativeQty', label: 'Cumulative', format: 'qty' },
          { key: 'rate', label: 'Rate', format: 'money' },
          { key: 'amount', label: 'Amount', format: 'money' },
        ],
      },
      actions: [
        { label: 'Approve & invoice client', path: (r) => `/ra-bills/${r.id}/approve`, when: (r) => ['draft', 'submitted'].includes(r.status), perm: 'construction.rabill.approve', confirm: 'Approve this RA bill? A client invoice will be posted.' },
        { label: 'Cancel', path: (r) => `/ra-bills/${r.id}/cancel`, when: (r) => r.status !== 'cancelled', perm: 'construction.rabill.delete', variant: 'danger', confirm: 'Cancel this RA bill? Approved bills are reversed in the ledger.' },
      ],
    },
  },
  equipment: {
    key: 'equipment',
    title: 'Equipment & Machinery',
    singular: 'Equipment',
    endpoint: '/equipment',
    perm: 'construction.equipment',
    importResource: 'equipment',
    searchable: true,
    editable: true,
    columns: [{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'type', label: 'Type' }, { key: 'ownership', label: 'Ownership', format: 'status' }, { key: 'hourlyRate', label: 'Hourly rate', format: 'money' }, statusCol()],
    form: {
      fields: [
        { name: 'code', label: 'Code', required: true },
        { name: 'name', label: 'Name', required: true },
        { name: 'type', label: 'Type', hint: 'Mixer, excavator, crane…' },
        { name: 'ownership', label: 'Ownership', type: 'select', options: ['owned', 'rented'], default: 'owned' },
        { name: 'hourlyRate', label: 'Hourly rate (BDT)', type: 'decimal', default: '0' },
        { ...projectField, name: 'currentProjectId', label: 'Current project' },
        { name: 'status', label: 'Status', type: 'select', options: ['available', 'in_use', 'maintenance', 'retired'], default: 'available' },
      ],
    },
  },

  // ---------------- Procurement ----------------
  'purchase-requisitions': {
    key: 'purchase-requisitions',
    title: 'Purchase Requisitions',
    singular: 'Purchase Requisition',
    endpoint: '/purchase-requisitions',
    perm: 'procurement.requisition',
    searchable: true,
    columns: [{ key: 'no', label: 'No.' }, { key: 'date', label: 'Date', format: 'date' }, { key: 'projectName', label: 'Project' }, { key: 'requiredBy', label: 'Required by', format: 'date' }, { key: 'lineCount', label: 'Lines' }, statusCol()],
    filters: [statusFilter(['draft', 'submitted', 'approved', 'ordered', 'rejected']), projectFilter],
    form: {
      fields: [
        { name: 'date', label: 'Date', type: 'date', required: true, default: today() },
        { name: 'requiredBy', label: 'Required by', type: 'date' },
        projectField,
        { name: 'warehouseId', label: 'Deliver to', type: 'select', source: warehouseSource },
        { name: 'remarks', label: 'Remarks', type: 'textarea', span: 4 },
      ],
      lines: qtyLines([{ name: 'estimatedRate', label: 'Est. rate', type: 'decimal', width: '15%' }, { name: 'remarks', label: 'Remarks', width: '25%' }]),
    },
    detail: {
      fields: [{ key: 'no', label: 'No.' }, { key: 'date', label: 'Date', format: 'date' }, { key: 'requiredBy', label: 'Required by', format: 'date' }, statusCol(), { key: 'remarks', label: 'Remarks' }],
      lines: { key: 'lines', columns: [{ key: 'itemCode', label: 'Code' }, { key: 'itemName', label: 'Item' }, { key: 'uom', label: 'Unit' }, { key: 'quantity', label: 'Qty', format: 'qty' }, { key: 'estimatedRate', label: 'Est. rate', format: 'money' }] },
      actions: [
        { label: 'Submit', path: (r) => `/purchase-requisitions/${r.id}/submit`, when: (r) => r.status === 'draft' },
        { label: 'Approve', path: (r) => `/purchase-requisitions/${r.id}/approve`, when: (r) => ['draft', 'submitted'].includes(r.status), perm: 'procurement.order.approve' },
        { label: 'Reject', path: (r) => `/purchase-requisitions/${r.id}/reject`, when: (r) => ['draft', 'submitted'].includes(r.status), perm: 'procurement.order.approve', variant: 'danger' },
      ],
      extra: (r) =>
        r.status === 'approved' ? (
          <Link href={`/m/purchase-orders/new?requisitionId=${r.id}`} className="text-sm text-brand-600 hover:underline">
            Create purchase order from this requisition →
          </Link>
        ) : null,
    },
  },
  'purchase-orders': {
    key: 'purchase-orders',
    title: 'Purchase Orders',
    singular: 'Purchase Order',
    endpoint: '/purchase-orders',
    perm: 'procurement.order',
    searchable: true,
    columns: [{ key: 'no', label: 'No.' }, { key: 'date', label: 'Date', format: 'date' }, { key: 'partyName', label: 'Supplier' }, { key: 'projectName', label: 'Project' }, { key: 'warehouse', label: 'Deliver to' }, { key: 'total', label: 'Total', format: 'money' }, statusCol()],
    filters: [statusFilter(['draft', 'approved', 'partially_received', 'received', 'closed', 'cancelled']), projectFilter],
    form: {
      fields: [
        { name: 'partyId', label: 'Supplier', type: 'select', source: partySource('vendor'), required: true },
        { name: 'date', label: 'Date', type: 'date', required: true, default: today() },
        { name: 'expectedDate', label: 'Expected delivery', type: 'date' },
        { name: 'warehouseId', label: 'Deliver to', type: 'select', source: warehouseSource, required: true },
        projectField,
        { name: 'terms', label: 'Terms & conditions', type: 'textarea', span: 3 },
      ],
      lines: {
        ...priceLines(true),
        columns: priceLines(true).columns.map((c) => (c.name === 'description' ? { ...c, label: 'Specification' } : c)),
      },
    },
    detail: {
      fields: [
        { key: 'no', label: 'PO No.' },
        { key: 'partyName', label: 'Supplier' },
        { key: 'date', label: 'Date', format: 'date' },
        { key: 'expectedDate', label: 'Expected', format: 'date' },
        { key: 'warehouse', label: 'Deliver to' },
        { key: 'projectName', label: 'Project' },
        { key: 'subtotal', label: 'Subtotal', format: 'money' },
        { key: 'vatAmount', label: 'VAT', format: 'money' },
        { key: 'total', label: 'Total', format: 'money' },
        statusCol(),
        { key: 'terms', label: 'Terms' },
      ],
      lines: {
        key: 'lines',
        columns: [
          { key: 'itemCode', label: 'Code' },
          { key: 'itemName', label: 'Item' },
          { key: 'uom', label: 'Unit' },
          { key: 'quantity', label: 'Ordered', format: 'qty' },
          { key: 'receivedQty', label: 'Received', format: 'qty' },
          { key: 'unitPrice', label: 'Rate', format: 'money' },
          { key: 'vatAmount', label: 'VAT', format: 'money' },
          { key: 'amount', label: 'Amount', format: 'money' },
        ],
      },
      actions: [
        { label: 'Approve', path: (r) => `/purchase-orders/${r.id}/approve`, when: (r) => r.status === 'draft', perm: 'procurement.order.approve' },
        { label: 'Close', path: (r) => `/purchase-orders/${r.id}/close`, when: (r) => ['approved', 'partially_received', 'received'].includes(r.status), variant: 'secondary', confirm: 'Close this PO? No further receipts will be allowed.' },
        { label: 'Cancel', path: (r) => `/purchase-orders/${r.id}/cancel`, when: (r) => ['draft', 'approved'].includes(r.status), variant: 'danger', confirm: 'Cancel this purchase order?' },
      ],
      extra: (r) => <GoodsReceiptPanel order={r} />,
    },
  },
  'goods-receipts': {
    key: 'goods-receipts',
    title: 'Goods Receipts (GRN)',
    singular: 'Goods Receipt',
    endpoint: '/goods-receipts',
    perm: 'procurement.receipt',
    searchable: true,
    createHref: '/m/purchase-orders?status=approved',
    columns: [
      { key: 'no', label: 'GRN No.' },
      { key: 'date', label: 'Date', format: 'date' },
      { key: 'partyName', label: 'Supplier' },
      { key: 'orderNo', label: 'PO' },
      { key: 'challanNo', label: 'Challan' },
      { key: 'warehouse', label: 'Warehouse' },
      { key: 'billed', label: 'Billed', format: 'bool' },
      statusCol(),
    ],
    detail: {
      fields: [{ key: 'no', label: 'GRN No.' }, { key: 'orderNo', label: 'PO' }, { key: 'partyName', label: 'Supplier' }, { key: 'date', label: 'Date', format: 'date' }, { key: 'warehouse', label: 'Warehouse' }, { key: 'challanNo', label: 'Challan' }, statusCol()],
      lines: { key: 'lines', columns: [{ key: 'itemCode', label: 'Code' }, { key: 'itemName', label: 'Item' }, { key: 'uom', label: 'Unit' }, { key: 'quantity', label: 'Qty', format: 'qty' }, { key: 'unitCost', label: 'Rate', format: 'money' }, { key: 'amount', label: 'Amount', format: 'money' }] },
      actions: [{ label: 'Create vendor bill', path: (r) => `/bills/from-receipt/${r.id}`, perm: 'finance.bill.create', redirect: (res) => `/m/bills/${res.id}` }],
    },
  },

  // ---------------- Inventory ----------------
  items: {
    key: 'items',
    title: 'Items & Materials',
    singular: 'Item',
    endpoint: '/items',
    perm: 'inventory.item',
    importResource: 'items',
    searchable: true,
    editable: true,
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name', label: 'Name' },
      { key: 'categoryName', label: 'Category' },
      { key: 'uom', label: 'Unit' },
      { key: 'onHand', label: 'On hand', format: 'qty' },
      { key: 'value', label: 'Stock value', format: 'money' },
      { key: 'reorderLevel', label: 'Reorder at', format: 'qty' },
      { key: 'type', label: 'Type', format: 'status' },
    ],
    filters: [
      { name: 'categoryId', label: 'Category', type: 'select', source: { lookup: 'itemCategories' } },
      { name: 'type', label: 'Type', type: 'select', options: ['stock', 'non_stock', 'service'] },
      { name: 'lowStock', label: 'Low stock only', type: 'select', options: [{ value: 'true', label: 'Yes' }] },
    ],
    form: {
      fields: [
        { name: 'code', label: 'Code', required: true },
        { name: 'name', label: 'Name', required: true, span: 2 },
        { name: 'type', label: 'Type', type: 'select', options: ['stock', 'non_stock', 'service'], default: 'stock' },
        { name: 'categoryId', label: 'Category', type: 'select', source: { lookup: 'itemCategories' } },
        { name: 'uomId', label: 'Unit', type: 'select', source: { lookup: 'uoms', label: (r) => `${r.code} — ${r.name}` }, required: true },
        { name: 'reorderLevel', label: 'Reorder level', type: 'decimal', default: '0' },
        { name: 'standardCost', label: 'Standard cost', type: 'decimal' },
        { name: 'defaultVatCodeId', label: 'Default VAT', type: 'select', source: vatSource },
        { name: 'specification', label: 'Specification', hint: 'e.g. 60 grade, 12mm', span: 3 },
        { name: 'description', label: 'Description', type: 'textarea', span: 4 },
        { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      ],
    },
  },
  warehouses: {
    key: 'warehouses',
    title: 'Warehouses & Site Stores',
    singular: 'Warehouse',
    endpoint: '/warehouses',
    perm: 'inventory.warehouse',
    importResource: 'warehouses',
    searchable: true,
    editable: true,
    columns: [{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'type', label: 'Type', format: 'status' }, { key: 'address', label: 'Address' }, { key: 'isActive', label: 'Active', format: 'bool' }],
    form: {
      fields: [
        { name: 'code', label: 'Code', required: true },
        { name: 'name', label: 'Name', required: true },
        { name: 'type', label: 'Type', type: 'select', options: ['central', 'site'], default: 'central' },
        { ...projectField, showIf: (v) => v.type === 'site' },
        { name: 'address', label: 'Address', type: 'textarea', span: 2 },
        { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      ],
    },
  },
  'item-categories': {
    key: 'item-categories',
    title: 'Item Categories',
    singular: 'Category',
    endpoint: '/item-categories',
    perm: 'inventory.item',
    editable: true,
    columns: [{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }],
    form: {
      fields: [
        { name: 'code', label: 'Code', required: true },
        { name: 'name', label: 'Name', required: true },
        { name: 'inventoryAccountId', label: 'Inventory account', type: 'select', source: accountSource((r) => r.type === 'asset') },
        { name: 'expenseAccountId', label: 'Consumption / expense account', type: 'select', source: accountSource((r) => r.type === 'expense') },
      ],
    },
  },
  uoms: {
    key: 'uoms',
    title: 'Units of Measure',
    singular: 'Unit',
    endpoint: '/uoms',
    perm: 'inventory.item',
    editable: true,
    columns: [{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }],
    form: { fields: [{ name: 'code', label: 'Code', required: true }, { name: 'name', label: 'Name', required: true }] },
  },
  'stock-documents': {
    key: 'stock-documents',
    title: 'Stock Documents',
    singular: 'Stock Document',
    endpoint: '/stock/documents',
    perm: 'inventory.movement',
    searchable: true,
    columns: [{ key: 'no', label: 'No.' }, { key: 'type', label: 'Type', format: 'status' }, { key: 'date', label: 'Date', format: 'date' }, { key: 'projectName', label: 'Project' }, { key: 'remarks', label: 'Remarks' }, statusCol()],
    filters: [{ name: 'type', label: 'Type', type: 'select', options: ['issue', 'transfer', 'adjustment', 'opening'] }, projectFilter],
    form: {
      postable: true,
      fields: [
        { name: 'type', label: 'Type', type: 'select', options: ['issue', 'transfer', 'adjustment', 'opening'], default: 'issue', required: true },
        { name: 'date', label: 'Date', type: 'date', required: true, default: today() },
        { name: 'fromWarehouseId', label: 'From warehouse', type: 'select', source: warehouseSource, showIf: (v) => v.type !== 'opening' },
        { name: 'toWarehouseId', label: 'To warehouse', type: 'select', source: warehouseSource, showIf: (v) => v.type === 'transfer' || v.type === 'opening' },
        { ...projectField, label: 'Issue to project', showIf: (v) => v.type === 'issue' },
        { name: 'remarks', label: 'Remarks', type: 'textarea', span: 4 },
      ],
      lines: {
        columns: [
          { name: 'itemId', label: 'Item', type: 'select', source: itemSource, width: '45%' },
          { name: 'quantity', label: 'Qty (± for adjustment)', type: 'decimal', width: '20%' },
          { name: 'unitCost', label: 'Unit cost (opening / + adj.)', type: 'decimal', width: '20%' },
        ],
        newLine: () => ({ itemId: '', quantity: '', unitCost: '' }),
      },
    },
    detail: {
      fields: [{ key: 'no', label: 'No.' }, { key: 'type', label: 'Type', format: 'status' }, { key: 'date', label: 'Date', format: 'date' }, statusCol(), { key: 'remarks', label: 'Remarks' }],
      lines: { key: 'lines', columns: [{ key: 'itemCode', label: 'Code' }, { key: 'itemName', label: 'Item' }, { key: 'uom', label: 'Unit' }, { key: 'quantity', label: 'Qty', format: 'qty' }, { key: 'unitCost', label: 'Unit cost', format: 'money' }] },
      actions: [
        { label: 'Post', path: (r) => `/stock/documents/${r.id}/post`, when: (r) => r.status === 'draft', perm: 'inventory.movement.create' },
        { label: 'Delete draft', path: (r) => `/stock/documents/${r.id}`, method: 'delete', when: (r) => r.status === 'draft', variant: 'danger', confirm: 'Delete this draft?', redirect: () => '/m/stock-documents' },
      ],
    },
  },

  // ---------------- Finance ----------------
  parties: {
    key: 'parties',
    title: 'Customers, Vendors & Subcontractors',
    singular: 'Party',
    endpoint: '/parties',
    perm: 'finance.party',
    importResource: 'parties',
    attachEntity: 'party',
    searchable: true,
    editable: true,
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name', label: 'Name' },
      { key: 'type', label: 'Type', format: 'status' },
      { key: 'phone', label: 'Phone' },
      { key: 'binNo', label: 'BIN' },
      { key: 'receivable', label: 'Receivable', format: 'money' },
      { key: 'payable', label: 'Payable', format: 'money' },
    ],
    filters: [{ name: 'type', label: 'Type', type: 'select', options: ['customer', 'vendor', 'subcontractor'] }],
    form: {
      fields: [
        { name: 'type', label: 'Type', type: 'select', options: ['customer', 'vendor', 'subcontractor'], required: true, default: 'vendor' },
        { name: 'code', label: 'Code', hint: 'Blank = auto', createOnly: true },
        { name: 'name', label: 'Name', required: true, span: 2 },
        { name: 'contactPerson', label: 'Contact person' },
        { name: 'phone', label: 'Phone' },
        { name: 'email', label: 'Email', type: 'email' },
        { name: 'binNo', label: 'BIN (VAT)' },
        { name: 'tin', label: 'TIN' },
        { name: 'tradeLicense', label: 'Trade license' },
        { name: 'paymentTermsDays', label: 'Payment terms (days)', type: 'number', default: 30 },
        { name: 'creditLimit', label: 'Credit limit', type: 'decimal' },
        { name: 'defaultTdsCodeId', label: 'Default TDS', type: 'select', source: { lookup: 'taxCodes', filter: (r) => r.kind === 'tds' } },
        { name: 'defaultVdsCodeId', label: 'Default VDS', type: 'select', source: { lookup: 'taxCodes', filter: (r) => r.kind === 'vds' } },
        { name: 'address', label: 'Address', type: 'textarea', span: 4 },
        { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      ],
    },
  },
  invoices: {
    key: 'invoices',
    title: 'Sales Invoices',
    singular: 'Invoice',
    endpoint: '/invoices',
    perm: 'finance.invoice',
    searchable: true,
    columns: [
      { key: 'no', label: 'No.' },
      { key: 'date', label: 'Date', format: 'date' },
      { key: 'partyName', label: 'Customer' },
      { key: 'projectName', label: 'Project' },
      { key: 'total', label: 'Receivable', format: 'money' },
      { key: 'paidAmount', label: 'Received', format: 'money' },
      statusCol(),
    ],
    filters: [statusFilter(['draft', 'posted', 'partially_paid', 'paid', 'cancelled']), projectFilter],
    form: {
      postable: true,
      fields: [
        { name: 'partyId', label: 'Customer', type: 'select', source: partySource('customer'), required: true, span: 2 },
        { name: 'date', label: 'Date', type: 'date', required: true, default: today() },
        { name: 'dueDate', label: 'Due date', type: 'date' },
        projectField,
        { name: 'mushakNo', label: 'Mushak-6.3 No.' },
        { name: 'retentionAmount', label: 'Retention held by client', type: 'decimal', default: '0' },
        { name: 'advanceAdjustment', label: 'Advance adjusted', type: 'decimal', default: '0' },
        { name: 'notes', label: 'Notes', type: 'textarea', span: 4 },
      ],
      lines: priceLines(true, 'income'),
    },
    detail: {
      fields: [
        { key: 'no', label: 'Invoice No.' },
        { key: 'partyName', label: 'Customer' },
        { key: 'partyBin', label: 'Customer BIN' },
        { key: 'date', label: 'Date', format: 'date' },
        { key: 'dueDate', label: 'Due', format: 'date' },
        { key: 'projectName', label: 'Project' },
        { key: 'mushakNo', label: 'Mushak-6.3' },
        statusCol(),
        { key: 'subtotal', label: 'Subtotal', format: 'money' },
        { key: 'vatAmount', label: 'VAT', format: 'money' },
        { key: 'retentionAmount', label: 'Less retention', format: 'money' },
        { key: 'advanceAdjustment', label: 'Less advance', format: 'money' },
        { key: 'total', label: 'Receivable', format: 'money' },
        { key: 'paidAmount', label: 'Received', format: 'money' },
        docLink('/m/journals', 'journalEntryId', 'Journal entry'),
      ],
      lines: { key: 'lines', columns: [{ key: 'description', label: 'Description' }, { key: 'quantity', label: 'Qty', format: 'qty' }, { key: 'unitPrice', label: 'Rate', format: 'money' }, { key: 'amount', label: 'Amount', format: 'money' }, { key: 'vatAmount', label: 'VAT', format: 'money' }] },
      actions: [
        { label: 'Post', path: (r) => `/invoices/${r.id}/post`, when: (r) => r.status === 'draft', perm: 'finance.invoice.create' },
        { label: 'Cancel', path: (r) => `/invoices/${r.id}/cancel`, when: (r) => ['draft', 'posted'].includes(r.status) && !r.raBillId, perm: 'finance.invoice.delete', variant: 'danger', confirm: 'Cancel this invoice? Posted entries will be reversed.' },
      ],
    },
  },
  bills: {
    key: 'bills',
    title: 'Vendor Bills',
    singular: 'Bill',
    endpoint: '/bills',
    perm: 'finance.bill',
    searchable: true,
    columns: [
      { key: 'no', label: 'No.' },
      { key: 'vendorRef', label: 'Vendor ref' },
      { key: 'date', label: 'Date', format: 'date' },
      { key: 'partyName', label: 'Vendor' },
      { key: 'projectName', label: 'Project' },
      { key: 'total', label: 'Payable', format: 'money' },
      { key: 'paidAmount', label: 'Paid', format: 'money' },
      statusCol(),
    ],
    filters: [statusFilter(['draft', 'posted', 'partially_paid', 'paid', 'cancelled']), projectFilter],
    form: {
      postable: true,
      fields: [
        { name: 'partyId', label: 'Vendor / subcontractor', type: 'select', source: { ...partySource(), filter: (r) => r.type !== 'customer' }, required: true, span: 2 },
        { name: 'vendorRef', label: 'Vendor invoice no.' },
        { name: 'date', label: 'Date', type: 'date', required: true, default: today() },
        { name: 'dueDate', label: 'Due date', type: 'date' },
        projectField,
        { name: 'notes', label: 'Notes', type: 'textarea', span: 4 },
      ],
      lines: priceLines(true, 'expense'),
    },
    detail: {
      fields: [
        { key: 'no', label: 'Bill No.' },
        { key: 'partyName', label: 'Vendor' },
        { key: 'vendorRef', label: 'Vendor ref' },
        { key: 'date', label: 'Date', format: 'date' },
        { key: 'projectName', label: 'Project' },
        statusCol(),
        { key: 'subtotal', label: 'Subtotal', format: 'money' },
        { key: 'vatAmount', label: 'VAT', format: 'money' },
        { key: 'retentionAmount', label: 'Less retention', format: 'money' },
        { key: 'total', label: 'Payable', format: 'money' },
        { key: 'paidAmount', label: 'Paid', format: 'money' },
        docLink('/m/journals', 'journalEntryId', 'Journal entry'),
      ],
      lines: { key: 'lines', columns: [{ key: 'description', label: 'Description' }, { key: 'quantity', label: 'Qty', format: 'qty' }, { key: 'unitPrice', label: 'Rate', format: 'money' }, { key: 'amount', label: 'Amount', format: 'money' }, { key: 'vatAmount', label: 'VAT', format: 'money' }] },
      actions: [
        { label: 'Post', path: (r) => `/bills/${r.id}/post`, when: (r) => r.status === 'draft', perm: 'finance.bill.create' },
        { label: 'Cancel', path: (r) => `/bills/${r.id}/cancel`, when: (r) => ['draft', 'posted'].includes(r.status) && !r.subcontractBillId, perm: 'finance.bill.delete', variant: 'danger', confirm: 'Cancel this bill? Posted entries will be reversed.' },
      ],
    },
  },
  payments: {
    key: 'payments',
    title: 'Receipts & Payments',
    singular: 'Payment',
    endpoint: '/payments',
    perm: 'finance.payment',
    searchable: true,
    createHref: '/finance/payments/new',
    columns: [
      { key: 'no', label: 'No.' },
      { key: 'direction', label: 'Type', render: (r) => (r.direction === 'in' ? 'Receipt' : 'Payment') },
      { key: 'date', label: 'Date', format: 'date' },
      { key: 'partyName', label: 'Party' },
      { key: 'method', label: 'Method', format: 'status' },
      { key: 'accountName', label: 'Cash/Bank' },
      { key: 'amount', label: 'Gross', format: 'money' },
      { key: 'tdsAmount', label: 'TDS', format: 'money' },
      { key: 'vdsAmount', label: 'VDS', format: 'money' },
      statusCol(),
    ],
    filters: [{ name: 'type', label: 'Type', type: 'select', options: [{ value: 'in', label: 'Receipts' }, { value: 'out', label: 'Payments' }] }],
    detail: {
      fields: [
        { key: 'no', label: 'No.' },
        { key: 'direction', label: 'Type', render: (r) => (r.direction === 'in' ? 'Receipt' : 'Payment') },
        { key: 'partyName', label: 'Party' },
        { key: 'date', label: 'Date', format: 'date' },
        { key: 'method', label: 'Method', format: 'status' },
        { key: 'chequeNo', label: 'Cheque no.' },
        { key: 'accountName', label: 'Cash/Bank' },
        statusCol(),
        { key: 'amount', label: 'Gross amount', format: 'money' },
        { key: 'tdsAmount', label: 'TDS', format: 'money' },
        { key: 'vdsAmount', label: 'VDS', format: 'money' },
        { key: 'netAmount', label: 'Net cash', format: 'money' },
      ],
      lines: {
        key: 'allocations',
        columns: [
          { key: 'doc', label: 'Document', render: (r) => (r.invoiceId ? <Link className="text-brand-600" href={`/m/invoices/${r.invoiceId}`}>{r.invoiceNo}</Link> : <Link className="text-brand-600" href={`/m/bills/${r.billId}`}>{r.billNo}</Link>) },
          { key: 'amount', label: 'Allocated', format: 'money' },
        ],
      },
      actions: [{ label: 'Cancel', path: (r) => `/payments/${r.id}/cancel`, when: (r) => r.status === 'posted', perm: 'finance.payment.delete', variant: 'danger', confirm: 'Cancel this payment? Allocations and ledger entries will be reversed.' }],
    },
  },
  journals: {
    key: 'journals',
    title: 'Journal Entries',
    singular: 'Journal Entry',
    endpoint: '/journals',
    perm: 'finance.journal',
    searchable: true,
    columns: [
      { key: 'no', label: 'No.' },
      { key: 'date', label: 'Date', format: 'date' },
      { key: 'sourceType', label: 'Source', format: 'status' },
      { key: 'reference', label: 'Reference' },
      { key: 'narration', label: 'Narration' },
      { key: 'totalDebit', label: 'Amount', format: 'money' },
      statusCol(),
    ],
    filters: [statusFilter(['draft', 'posted', 'reversed']), { name: 'type', label: 'Source', type: 'select', options: ['manual', 'invoice', 'bill', 'sub_bill', 'payment', 'grn', 'stock', 'payroll', 'payroll_payment'] }],
    form: {
      postable: true,
      fields: [
        { name: 'date', label: 'Date', type: 'date', required: true, default: today() },
        { name: 'reference', label: 'Reference' },
        { name: 'narration', label: 'Narration', span: 2 },
      ],
      lines: {
        columns: [
          { name: 'accountId', label: 'Account', type: 'select', source: accountSource(), width: '30%' },
          { name: 'debit', label: 'Debit', type: 'decimal', width: '13%' },
          { name: 'credit', label: 'Credit', type: 'decimal', width: '13%' },
          { name: 'partyId', label: 'Party', type: 'select', source: partySource(), width: '17%' },
          { name: 'projectId', label: 'Project', type: 'select', source: { lookup: 'projects', label: (r) => r.code }, width: '12%' },
          { name: 'description', label: 'Memo', width: '15%' },
        ],
        newLine: () => ({ accountId: '', debit: '', credit: '', partyId: '', projectId: '', description: '' }),
      },
    },
    detail: {
      fields: [{ key: 'no', label: 'No.' }, { key: 'date', label: 'Date', format: 'date' }, { key: 'sourceType', label: 'Source', format: 'status' }, { key: 'reference', label: 'Reference' }, statusCol(), { key: 'totalDebit', label: 'Total', format: 'money' }, { key: 'narration', label: 'Narration' }],
      lines: {
        key: 'lines',
        columns: [
          { key: 'account', label: 'Account', render: (r) => `${r.accountCode} — ${r.accountName}` },
          { key: 'description', label: 'Memo' },
          { key: 'partyName', label: 'Party' },
          { key: 'projectName', label: 'Project' },
          { key: 'debit', label: 'Debit', format: 'money' },
          { key: 'credit', label: 'Credit', format: 'money' },
        ],
      },
      actions: [
        { label: 'Post', path: (r) => `/journals/${r.id}/post`, when: (r) => r.status === 'draft', perm: 'finance.journal.post' },
        { label: 'Reverse', path: (r) => `/journals/${r.id}/reverse`, when: (r) => r.status === 'posted' && r.sourceType === 'manual', perm: 'finance.journal.post', variant: 'secondary', confirm: 'Post a reversing entry dated today?', redirect: (res) => `/m/journals/${res.id}` },
        { label: 'Delete draft', path: (r) => `/journals/${r.id}`, method: 'delete', when: (r) => r.status === 'draft', variant: 'danger', confirm: 'Delete this draft?', redirect: () => '/m/journals' },
      ],
    },
  },
  'tax-codes': {
    key: 'tax-codes',
    title: 'VAT / TDS / VDS Codes',
    singular: 'Tax Code',
    endpoint: '/tax-codes',
    perm: 'finance.account',
    editable: true,
    columns: [{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'kind', label: 'Kind', format: 'status' }, { key: 'rate', label: 'Rate %', format: 'qty' }, { key: 'section', label: 'Section' }, { key: 'isActive', label: 'Active', format: 'bool' }],
    form: {
      fields: [
        { name: 'code', label: 'Code', required: true },
        { name: 'name', label: 'Name', required: true },
        { name: 'kind', label: 'Kind', type: 'select', options: ['vat', 'tds', 'vds'], required: true },
        { name: 'rate', label: 'Rate %', type: 'decimal', required: true },
        { name: 'section', label: 'Section / service code' },
        { name: 'accountId', label: 'GL account', type: 'select', source: accountSource() },
        { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      ],
    },
  },

  // ---------------- Admin ----------------
  users: {
    key: 'users',
    title: 'Users',
    singular: 'User',
    endpoint: '/users',
    perm: 'core.user',
    searchable: true,
    editable: true,
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'roles', label: 'Roles', render: (r) => (r.roles as { name: string }[] | undefined)?.map((x) => x.name).join(', ') },
      { key: 'lastLoginAt', label: 'Last login', format: 'datetime' },
      { key: 'isActive', label: 'Active', format: 'bool' },
    ],
    form: {
      fields: [
        { name: 'name', label: 'Name', required: true },
        { name: 'email', label: 'Email', type: 'email', required: true },
        { name: 'phone', label: 'Phone' },
        { name: 'password', label: 'Password', type: 'password', hint: 'Min 8 chars. Leave blank to keep current.' },
        { name: 'branchId', label: 'Branch', type: 'select', source: { lookup: 'branches' } },
        { name: 'employeeId', label: 'Linked employee', type: 'select', source: employeeSource },
        { name: 'roleIds', label: 'Roles', type: 'multi', source: { lookup: 'roles' }, span: 4, default: [] },
        { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      ],
    },
  },
  branches: {
    key: 'branches',
    title: 'Branches',
    singular: 'Branch',
    endpoint: '/branches',
    perm: 'core.branch',
    editable: true,
    columns: [{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'binNo', label: 'BIN' }, { key: 'phone', label: 'Phone' }, { key: 'isActive', label: 'Active', format: 'bool' }],
    form: {
      fields: [
        { name: 'code', label: 'Code', required: true },
        { name: 'name', label: 'Name', required: true },
        { name: 'binNo', label: 'BIN' },
        { name: 'phone', label: 'Phone' },
        { name: 'address', label: 'Address', type: 'textarea', span: 2 },
        { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      ],
    },
  },
};

